### ISSUE TITLE
Modify and deletion of objects

### ISSUE THREAD

**Issue by crosson** [datacenter/acirb#1]
I hate to ask since it is probably obvious but I think a few more examples of adding, deleting and modifying objects should be dropped into the rspec file or in the examples folder.

For example if I try to delete a static path in an EPG using object.destroy() I get the following error.

RuntimeError: Error response from APIC (170): "Admin implicit props cannot be modified, class=fvRsPathAtt

I am sure part of this has to do with my understanding of the ACI API and how I am probably incorrectly using it. It couldn't hurt to have a few more examples of adding, removing, and manipulating objects. Either in the examples folder or evne better in the rspec file. That would totally rock. :)

**Comment by paullesiak** [comment]
crosson, You're definitely right that the documentation is a bit sparse - my apologies for that. I will add those as you suggested.

To immediately answer your question, looks like this is a bug with the destroy() method, passing in administrative properties (in this case configSt), with the deletion property. To get around this, you can do the following using Naming.get_mo_from_dn:

```
  # find the EPG containing the path attach
  epg = @rest.lookupByDn('uni/tn-%s/ap-%s/epg-%s' % [testtenant, 'app1', 'epg1'], subtree: 'full')
  # perform a query to get the fvRsPathAtt
  dnq = ACIrb::DnQuery.new(epg.dn)
  dnq.class_filter = 'fvRsPathAtt'
  dnq.query_target = 'children'
  pathatt = @rest.query(dnq)[0]

  # here is the workaround: create a new Mo object from the pathDn, which won't include administrative properties
  pathatt = ACIrb::Naming.get_mo_from_dn(pathatt.dn)
  pathatt.destroy(@rest)
```

I'll mark this as a bug. Please let me know if this workaround will cover your use case and thanks for opening the issue

**Comment by paullesiak** [comment]
Accidentally closed -- reopening

**Comment by paullesiak** [comment]
crosson, the latest committed change should resolve your issue. Have also started adding more docstrings, but it's really time consuming -- maybe over the weekend, with a bottle of scotch, I can get documentation up to a point that at least isn't embarassing.

**Comment by crosson** [comment]
Paul this is fantastic. I didn't get a chance to test your work around today in my lab and now it sounds like I won't need to. I'll follow up next week with my results but if you are confident in your fix feel free to close this out! Thank you so much!

I approve the bottle of scotch work session!
