### ISSUE TITLE
ACIrb backwards compatibality?

### ISSUE THREAD

**Issue by jonstacks** [datacenter/acirb#12]
Hi @mtimm or @paullesiak,

I had a quick question for you guys. It seems like the `acirb` code version has to match the version that is installed on the APIC exactly and is not backwards compatible. Can you confirm if this is the case?

**Comment by paullesiak** [comment]
@jonstacks13, yes that is usually the case. It's not specific to ACIrb, but rather the underlying object model that defines the objects, properties, etc, in ACI. Typically newer versions of the object model will be backwards compatible with older releases, but that is not guaranteed. 

The best practice is to match ACIrb with APIC.

**Comment by mtimm** [comment]
@paullesiak I would modestly suggest that if we find any backwards incompatibility that it would be a bug with the underlying model.

**Comment by jonstacks** [comment]
@paullesiak and @mtimm,

Thanks for the quick responses!

To let you know where I'm coming from and my concern, we have about 2 or 3 different versions of ACI deployed currently and I believe the may grow even larger at some point. We have been doing a lot of development around ACI recently both in python and ruby. Here is the main scenario I'm worried about and that we have run into with the `acicobra` and `acimodel` packages.
1. We have an APIC on version X lets say.
2. We deploy a lot of automation around that APIC with the scripts depending on `acirb` version X which matches the APIC.
3. We upgrade the version of the APIC to the next release, Y, and it breaks all the deployed automation.

Also, have you guys developed a best practice when developing your own internal gems that make use of `acirb`? So far when we have been developing our own internal gems for automation, we commonly have a line like this in our gemspec:

```
s.add_runtime_dependency 'acirb'
```

When we try to deploy our application though, we have to manually change the version of `acirb` in our application's Gemfile to match the version of code that is running on the APIC. This is sort of a pain point when trying to automate deploying our code across multiple environments with different ACI versions. Any suggestions would be appreciated.

**Comment by mtimm** [comment]
Disclaimer:  I don't use acirb, while @paullesiak originally put it together I am not sure he is still using it in any capacity.

The proper sequence of events for what you describe is to update acicobra/acimodel or acirb to match the latest version of ACI you have in your environments.  They _should_ be backwards compatible and no breakage should be seen.  If you do see breakage then it is either a bug (regression) or the functionality of acicobra/acimodel and/or acirb that you were utilizing relied on what was considered a bug in those modules/gem.  The most common one seen these days is with acicobra/acimodel where you used to be able to add polUni to a MoDirectory but now you can not.  This breaks all kinds of previously developed scripts unfortunately.  There is an issue that @alok806 opened in the github cobra repo for this.

**Comment by JerrodCarpenter** [comment]
I think @jonstacks13 is speaking of a versioning practice, or pattern, in which one can be rely on to tell them about the nature of changes.

[Semantic versioning](http://guides.rubygems.org/patterns/#semantic-versioning) seems to be among the favorites in the Ruby community.

Specifically this:
- PATCH 0.0.x level changes for implementation level detail changes, such as small bug fixes
- MINOR 0.x.0 level changes for any backwards _compatible_ API changes, such as new functionality/features
- MAJOR x.0.0 level changes for backwards _incompatible_ API changes, such as changes that will break existing users code if they update

**Comment by mtimm** [comment]
In this case semantic versioning doesn't make much sense.  Ideally we would follow the APIC/ACI versioning scheme and assume backwards compatibility just works unless proven otherwise.  Keep the SDK's at the latest versions and you should be ok.  That may not be ideal for ruby or python based versioning schemes but it is ideal to keep sanity with the base product these SDK's are designed to run against.

**Comment by paullesiak** [comment]
Since ACIrb is directly following the REST API of APIC, ACIrb effectively becomes unversioned and directly maps to the APIC version -- which is what it does as best as gem versioning standards allow. I think that @anvega is closer to the APIC versioning, etc, and may be able to provide more insight.

**Comment by paullesiak** [comment]
One more note -- I did reserve the patch.patch of versions to allow for there to be patches to ACIrb, so effectively we have <APIC MAJOR>.<APIC MINOR>.<APIC PATCH>.<ACIRB PATCH> in versioning strings.

Does that make sense?

**Comment by jonstacks** [comment]
I get why it is being versioned along with the APIC versions. I guess I see it more of as a client and server API issue though.

> The proper sequence of events for what you describe is to update acicobra/acimodel or acirb to match the latest version of ACI you have in your environments

This seems like an operational challenge if I have to update every single client in a given environment when I update the APIC code. Also, what about for client applications that span multiple APICs? Consider a NOC-like application that manages the health of your environments across multiple ACI deployments.

> The most common one seen these days is with acicobra/acimodel where you used to be able to add polUni to a MoDirectory but now you can not. This breaks all kinds of previously developed scripts unfortunately

When there are these breaking changes, is there any way to support multiple versions of the API? Many servers do this through either an explicit `/v1/` in the uri or through an accept header. This way no existing clients are impacted by the changes.

**Comment by mtimm** [comment]
For cobra a bunch of this is likely to change.  The original design that utilizes a model package is not ideal.  There is a bunch of work that has to be done to make what we are thinking a reality though so I can't commit to it being done anytime soon.  The idea would be that the SDK would remain the same and download metadata from the APIC it connects to that helps it interact with the model.

There is a way to have multiple versions of the API - through virtual environments.  I don't consider this a solution but it can work.

For the breaking change I mentioned, there is another approach to avoid this specific issue.  Some of it is already implemented in the APIC CLI that came with the 1.2 release, it just needs to be utilized by cobra.  acirb is not in my scope of understanding to be able to suggest what could or could not be done here for that.

**Comment by jonstacks** [comment]
@mtimm,

Is there a timeline on these changes and whether or not they will be breaking? We've invested heavily into learning these model based APIs in addition to the current REST API.
