### ISSUE TITLE
Uncaught exception when attempting to destroy managed object

### ISSUE THREAD

**Issue by JerrodCarpenter** [datacenter/acirb#14]
Version: `* acirb (1.2.1.0)`
Getting: `NoMethodError: undefined method '[]' for nil:NilClass`, when attempting to destroy a managed object.

[Process and Error](http://pastebin.com/HyyjME5q)

If it's a matter of process I'd appreciate the help!

**Comment by JerrodCarpenter** [comment]
Hey @paullesiak, do I need to call some other function to destroy a static path binding?

**Comment by bksteiny** [comment]
BTW @paullesiak, this error is noticed against version [1.2(2h)](http://www.cisco.com/c/en/us/td/docs/switches/datacenter/aci/apic/sw/1-x/release/notes/apic_rn_122h.html) but works against 1.1(2i)

cc: @kecorbin
