### ISSUE TITLE
REST methods question

### ISSUE THREAD

**Issue by craigbruenderman** [datacenter/acirb#5]
From what I can tell, the ACI API doesn't make use of PUT for updates, but rather uses a modified version of POST. Can anyone elaborate on why this is?

**Comment by paullesiak** [comment]
Craig, is this an issue with acirb? If it's a generic APIC question please open a TAC case, or refer to the API user guide here: http://www.cisco.com/c/en/us/td/docs/switches/datacenter/aci/apic/sw/1-x/api/rest/b_APIC_RESTful_API_User_Guide/b_IFC_RESTful_API_User_Guide_chapter_010.html#concept_21284AACF779429A8E6EEED11D143716

**Comment by mtimm** [comment]
No response from the submitter in almost 2 months.  This can be reopened if a response is provided.  

My take - PUT is not supported in ACI.  There is lots of debate on if PUT is really required for RESTful API's.  The bottom line is that the way the ACI RESTful API has been designed, PUT has virtually no value.  It would be very difficult, based on the ACI REST API design, to support an idempotent operation for create or update.
